name    'gusson/autofs'
version '1.1.0'
source 'git://github.com/gusson/puppet-module-autofs.git'
author 'gusson'
license 'Apache License, Version 2.0'
summary 'module to manage autofs'
description 'Provides the means to manage autofs on all systems.'
project_page 'https://github.com/gusson/puppet-module-autofs'

dependency 'puppetlabs/stdlib', '>= 4.6.x'
